/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutRecordRouteImport } from './routes/_layout/record'
import { Route as LayoutPriceRouteImport } from './routes/_layout/price'
import { Route as LayoutModel_transformRouteImport } from './routes/_layout/model_transform'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutCustom_fieldsRouteImport } from './routes/_layout/custom_fields'
import { Route as LayoutApi_keyRouteImport } from './routes/_layout/api_key'
import { Route as LayoutAccess_controlRouteImport } from './routes/_layout/access_control'
import { Route as LayoutSplatRouteImport } from './routes/_layout/$'
import { Route as LayoutProviderIndexRouteImport } from './routes/_layout/provider/index'
import { Route as LayoutProviderNewRouteImport } from './routes/_layout/provider/new'
import { Route as LayoutProviderEditIdRouteImport } from './routes/_layout/provider/edit.$id'
import { Route as LayoutModelEditIdRouteImport } from './routes/_layout/model/edit.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecordRoute = LayoutRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPriceRoute = LayoutPriceRouteImport.update({
  id: '/price',
  path: '/price',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModel_transformRoute = LayoutModel_transformRouteImport.update({
  id: '/model_transform',
  path: '/model_transform',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCustom_fieldsRoute = LayoutCustom_fieldsRouteImport.update({
  id: '/custom_fields',
  path: '/custom_fields',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApi_keyRoute = LayoutApi_keyRouteImport.update({
  id: '/api_key',
  path: '/api_key',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccess_controlRoute = LayoutAccess_controlRouteImport.update({
  id: '/access_control',
  path: '/access_control',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSplatRoute = LayoutSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProviderIndexRoute = LayoutProviderIndexRouteImport.update({
  id: '/provider/',
  path: '/provider/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProviderNewRoute = LayoutProviderNewRouteImport.update({
  id: '/provider/new',
  path: '/provider/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProviderEditIdRoute = LayoutProviderEditIdRouteImport.update({
  id: '/provider/edit/$id',
  path: '/provider/edit/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModelEditIdRoute = LayoutModelEditIdRouteImport.update({
  id: '/model/edit/$id',
  path: '/model/edit/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/$': typeof LayoutSplatRoute
  '/access_control': typeof LayoutAccess_controlRoute
  '/api_key': typeof LayoutApi_keyRoute
  '/custom_fields': typeof LayoutCustom_fieldsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/model_transform': typeof LayoutModel_transformRoute
  '/price': typeof LayoutPriceRoute
  '/record': typeof LayoutRecordRoute
  '/': typeof LayoutIndexRoute
  '/provider/new': typeof LayoutProviderNewRoute
  '/provider': typeof LayoutProviderIndexRoute
  '/model/edit/$id': typeof LayoutModelEditIdRoute
  '/provider/edit/$id': typeof LayoutProviderEditIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$': typeof LayoutSplatRoute
  '/access_control': typeof LayoutAccess_controlRoute
  '/api_key': typeof LayoutApi_keyRoute
  '/custom_fields': typeof LayoutCustom_fieldsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/model_transform': typeof LayoutModel_transformRoute
  '/price': typeof LayoutPriceRoute
  '/record': typeof LayoutRecordRoute
  '/': typeof LayoutIndexRoute
  '/provider/new': typeof LayoutProviderNewRoute
  '/provider': typeof LayoutProviderIndexRoute
  '/model/edit/$id': typeof LayoutModelEditIdRoute
  '/provider/edit/$id': typeof LayoutProviderEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/$': typeof LayoutSplatRoute
  '/_layout/access_control': typeof LayoutAccess_controlRoute
  '/_layout/api_key': typeof LayoutApi_keyRoute
  '/_layout/custom_fields': typeof LayoutCustom_fieldsRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/model_transform': typeof LayoutModel_transformRoute
  '/_layout/price': typeof LayoutPriceRoute
  '/_layout/record': typeof LayoutRecordRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/provider/new': typeof LayoutProviderNewRoute
  '/_layout/provider/': typeof LayoutProviderIndexRoute
  '/_layout/model/edit/$id': typeof LayoutModelEditIdRoute
  '/_layout/provider/edit/$id': typeof LayoutProviderEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/$'
    | '/access_control'
    | '/api_key'
    | '/custom_fields'
    | '/dashboard'
    | '/model_transform'
    | '/price'
    | '/record'
    | '/'
    | '/provider/new'
    | '/provider'
    | '/model/edit/$id'
    | '/provider/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$'
    | '/access_control'
    | '/api_key'
    | '/custom_fields'
    | '/dashboard'
    | '/model_transform'
    | '/price'
    | '/record'
    | '/'
    | '/provider/new'
    | '/provider'
    | '/model/edit/$id'
    | '/provider/edit/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/$'
    | '/_layout/access_control'
    | '/_layout/api_key'
    | '/_layout/custom_fields'
    | '/_layout/dashboard'
    | '/_layout/model_transform'
    | '/_layout/price'
    | '/_layout/record'
    | '/_layout/'
    | '/_layout/provider/new'
    | '/_layout/provider/'
    | '/_layout/model/edit/$id'
    | '/_layout/provider/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/record': {
      id: '/_layout/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof LayoutRecordRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/price': {
      id: '/_layout/price'
      path: '/price'
      fullPath: '/price'
      preLoaderRoute: typeof LayoutPriceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/model_transform': {
      id: '/_layout/model_transform'
      path: '/model_transform'
      fullPath: '/model_transform'
      preLoaderRoute: typeof LayoutModel_transformRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/custom_fields': {
      id: '/_layout/custom_fields'
      path: '/custom_fields'
      fullPath: '/custom_fields'
      preLoaderRoute: typeof LayoutCustom_fieldsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api_key': {
      id: '/_layout/api_key'
      path: '/api_key'
      fullPath: '/api_key'
      preLoaderRoute: typeof LayoutApi_keyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/access_control': {
      id: '/_layout/access_control'
      path: '/access_control'
      fullPath: '/access_control'
      preLoaderRoute: typeof LayoutAccess_controlRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$': {
      id: '/_layout/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof LayoutSplatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/provider/': {
      id: '/_layout/provider/'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof LayoutProviderIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/provider/new': {
      id: '/_layout/provider/new'
      path: '/provider/new'
      fullPath: '/provider/new'
      preLoaderRoute: typeof LayoutProviderNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/provider/edit/$id': {
      id: '/_layout/provider/edit/$id'
      path: '/provider/edit/$id'
      fullPath: '/provider/edit/$id'
      preLoaderRoute: typeof LayoutProviderEditIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/model/edit/$id': {
      id: '/_layout/model/edit/$id'
      path: '/model/edit/$id'
      fullPath: '/model/edit/$id'
      preLoaderRoute: typeof LayoutModelEditIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutSplatRoute: typeof LayoutSplatRoute
  LayoutAccess_controlRoute: typeof LayoutAccess_controlRoute
  LayoutApi_keyRoute: typeof LayoutApi_keyRoute
  LayoutCustom_fieldsRoute: typeof LayoutCustom_fieldsRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutModel_transformRoute: typeof LayoutModel_transformRoute
  LayoutPriceRoute: typeof LayoutPriceRoute
  LayoutRecordRoute: typeof LayoutRecordRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProviderNewRoute: typeof LayoutProviderNewRoute
  LayoutProviderIndexRoute: typeof LayoutProviderIndexRoute
  LayoutModelEditIdRoute: typeof LayoutModelEditIdRoute
  LayoutProviderEditIdRoute: typeof LayoutProviderEditIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSplatRoute: LayoutSplatRoute,
  LayoutAccess_controlRoute: LayoutAccess_controlRoute,
  LayoutApi_keyRoute: LayoutApi_keyRoute,
  LayoutCustom_fieldsRoute: LayoutCustom_fieldsRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutModel_transformRoute: LayoutModel_transformRoute,
  LayoutPriceRoute: LayoutPriceRoute,
  LayoutRecordRoute: LayoutRecordRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProviderNewRoute: LayoutProviderNewRoute,
  LayoutProviderIndexRoute: LayoutProviderIndexRoute,
  LayoutModelEditIdRoute: LayoutModelEditIdRoute,
  LayoutProviderEditIdRoute: LayoutProviderEditIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
